### ISSUE TITLE
-[UIButton setEnabled:] must be used from main thread only

### ISSUE THREAD

**Issue by bob910078** [ayakix/Image-Picker#1]
Hi ayakix,
The project has a run time error only which is occurred in the first time run on my iOS 12 iPhone 7 in Xcode 10. Did u have any idea? 

```
if status == PHAuthorizationStatus.authorized {
                    self.openImagePickerButton.isEnabled = true      /// <--This line has run time err
                }
```

BTW, ur project is great!

**Comment by ayakix** [comment]
@bob910078 Thanks for reporting.

It was caused by the fact that IBOutlet was not set correctly.
I already fixed it. Please pull again.

Thanks!
